# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_count', models.IntegerField(default=0)),
                ('host_count', models.IntegerField(default=0)),
                ('vm_count', models.IntegerField(default=0)),
                ('total_backup', models.FloatField()),
            ],
        ),
    ]
