# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_timeout', models.BigIntegerField(default=600)),
            ],
        ),
    ]
