# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='session_timeout',
        ),
        migrations.AddField(
            model_name='settings',
            name='parameter',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
