# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('minute', models.CharField(max_length=2)),
                ('hour', models.CharField(max_length=2)),
                ('week', models.CharField(max_length=2)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=2)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
