# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170420_1918'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VM'),
        ),
    ]
