# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20170420_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='celery_beat_id',
            field=models.IntegerField(null=True),
        ),
    ]
