# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedule_celery_beat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='celery_beat_id',
            new_name='celery_sched_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='celery_task_id',
            field=models.IntegerField(null=True),
        ),
    ]
