# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_vm_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='last_backup',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='schedule',
        ),
    ]
