# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170420_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
