# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:13
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_vm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=512),
        ),
    ]
